### ISSUE TITLE
nvim -d does not work as expected

### ISSUE THREAD

**Issue by mcctuxic** [NTBBloodbath/doom-nvim#127]
Steps to reproduce:
Install doomnvim from the repo (development branch), do not change anything.

Call nvim several time to make all needed installations possible.

Call nvim -d <file1> <file2>.

In both tabs only file2 will be displayed.

(Previously I mapped this behaviour to changes I made to the configuration. But 
this problem "works out of the box".)

**Comment by osamuaoki** [comment]
I tried:
```
$ nvim -d file1 file2
```
For main branch, I can confirm both windows show file2.
```
$ nvim -u NONE -d file1 file2
```
I can confirm both file1 and file2 are shown.

So this is a real bug in custom start up ... probably bug in bufferline I guess.

Since you can press TAB and get functioning DIFF, this is minor issue.  So let"s see how dependency packages evolve for few more weeks or so.

Funny thing is bufferline is changing highlight things only recently.  Do you know when this started?

**Comment by mcctuxic** [comment]
Hi,

how can I help in fixing this bug instead of waiting "a few more weeks"
for an guessed external root (bufferline) to be fixed by its authors?

**Comment by osamuaoki** [comment]
Well,,,, you can help not asking tutoring like questions but dig in to the problem by yourself and coming out with solution (or at least hunting down root cause).  For me, this seems tough problem beyond my time and skill.   I am taking relaxed attitudes since I don't suffer much.

**Comment by NTBBloodbath** [comment]
Hi, sorry for the late reply. I was a bit occupied lately haha

I think that maybe it has something to do with our last executed command in our init file, which calls `bufdo e`. I'll dig on it so I can determine if the `bufdo e` is really needed or not so we can remove it from our init file.

**Comment by NTBBloodbath** [comment]
Should be fixed now, please update and feel free to reopen this issue if this still happens to you.

Regards

**Comment by mcctuxic** [comment]
Fixed! Thank you!
