### ISSUE TITLE
Add support for modeline

### ISSUE THREAD

**Issue by osamuaoki** [NTBBloodbath/doom-nvim#134]
Here is my thought.  If you agree, I will make a PR.

I know some distros (including Debian, I use) has been disabling modeline for security reason.

There is a "ciaranm/securemodelim/securemodelines" (VIML) to address this problem and I have been using this.  Try to find the latest situation before posting this message, I googled and found a closed issue https://github.com/neovim/neovim/issues/2865

        `modelineexpr` option exists in Nvim 0.4 / Vim 8.1 now, and it is disabled by default.

Considering we only care nvim 0.5, enabling `modelineexpr` is as safe as using "ciaranm/securemodelime" .  If adding another bloated wrapper variable is too much, how about adding it as another commented out example for global_variables in doom_config.lua .

**Comment by NTBBloodbath** [comment]
Hi, being honest I didn't know about this being a thing. Can you please explain what it does?

If it's safe enough and it's useful then we could add this.

> If adding another bloated wrapper variable is too much, how about adding it as another commented out example for global_variables in doom_config.lua .

Maybe we could add a new wrapper variable if you agree with this, otherwise we can simply add a commented out example that would be _almost_ the same thing IMO but I don't want to decide everything myself haha your opinion interests me too.

Regards
