### ISSUE TITLE
Feature request: use null-ls

### ISSUE THREAD

**Issue by NTBBloodbath** [NTBBloodbath/doom-nvim#138]
Initially [format.nvim](https://github.com/lukas-reineke/format.nvim) was a [formatter.nvim](https://github.com/mhartington/formatter.nvim) fork with an entire rewrite but it seems that it's not being maintained anymore so we should jump to [formatter.nvim](https://github.com/mhartington/formatter.nvim)

**Comment by ashincoder** [comment]
@NTBBloodbath How about [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim). Since it takes care of both the formatters and linters. Also it is pretty easy to define formatters compared to formatter.nvim. 

When I took a look at formatter.nvim (Correct me if I am wrong xD) what I understood was that we have to define all the args and stdout for formatters.

While in null-ls we can just define the names of the formatters and the rest will be taken care of.

**Comment by ashincoder** [comment]
I do have a my config where I had setup up null-ls. https://github.com/ashincoder/dots/blob/main/minivim/.config/nvim/lua/lsp/null_ls.lua

**Comment by connorgmeehan** [comment]
Resolved in doom v4.0.0 (`next/` branch)
