### ISSUE TITLE
Is it possible to use mouse=r and not select line numbers?

### ISSUE THREAD

**Issue by blakebarnett** [NTBBloodbath/doom-nvim#16]
I can't get used to using `y` to copy/paste, is it possible to use `set mouse=r` but still retain the ability to ignore line numbers somehow?

**Comment by NTBBloodbath** [comment]
Hey, for now it isn't possible in the main branch. In the develop branch it is, since there the doomrc has had some improvements to use Vimscript and edit Neovim things directly without touching the doom nvim source.

Currently the mouse setup is made to use the `a` mode when enabled but if you use the development branch, you can change it by adding `set mouse=r` in the [commands field](https://github.com/NTBBloodbath/doom-nvim/blob/develop/doomrc#L362-L368) at the doomrc.

**Comment by blakebarnett** [comment]
Thank you for responding quickly!

I found it in `~/.config/doom-nvim/lua/doom/default/init.lua`, I'll use that mechanism going forward though.

I'll see about trying the develop branch.

**Comment by NTBBloodbath** [comment]
Alright, I'll close this issue then :)
