### ISSUE TITLE
crash report creates empty log dump

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#186]
This is the creash report I get:

---
# Doom Nvim crash report

> Report date: 2021-10-24 21:39:55

## System and Doom Nvim information

- **OS**: Darwin
- **Neovim version**: 0.6.0 (dev)
- **Doom Nvim information**:
  - **version**: 3.2.0-beta2
  - **`doom_root` variable**: `/Users/hjalmarjakobsson/.config/doom-nvim`
  - **`doom_configs_root` variable**: `/Users/hjalmarjakobsson/.config/doom-nvim`

### Begin error log dump

```
```

**Comment by NTBBloodbath** [comment]
Hey, sorry for the delay, work has been taking a good bunch of my time very recently haha.

> @NTBBloodbath could you post a line from your log file on linux?

Sure thing, there you go

```
[INFO  dom 14 nov 2021 18:04:17] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:129: Successfully reloaded 'doom.modules.config.doom-lsp-installer' module
```

Mine format follows spanish date format and that's why `HH:MM:SS` is at the end instead of the year I guess? Maybe we should only care about filtering day, day number and month? They're in the same order for you and me so it would make sense :thinking:

I think we could go with an easy implementation in such case we filter only what I said, however let me know if you would prefer the other way (the resilient version that you shared), I'm pretty fine with both tbh :p

**Comment by connorgmeehan** [comment]
Ok I'll try make a PR tonight, I think I'll check for `day / day_number / month` and then `year` seperately within the `[ERROR/WARN ...]` match.

**Comment by connorgmeehan** [comment]
Hey @molleweide give this a go in the develop branch.  Let me know if you run into problems or if it's all working can you close the issue?   :)
