### ISSUE TITLE
How to add a linter for a language

### ISSUE THREAD

**Issue by nulloneguy** [NTBBloodbath/doom-nvim#199]
## how to make linter work?
 - Installed `eslint` globally via `npm`
 - Added `"eslint"` in `doom-config.lua` > `linters = { ... }` 
 - made `PackerCompile` 
 - restarted nvim 
 
 but it doesn't work.
Maybe a stupid question, but how to add a linter correctly?

![Screenshot_2021-10-25-11-36-33_1920x1080](https://user-images.githubusercontent.com/87767572/138736039-668edd1c-6bbc-4e9d-8528-55c7e20f7e92.png)

**Comment by jamesdury** [comment]
I'm having some trouble to get this to work at all.

I'm on the `develop` branch and have:

added `eslint` like original ticket
enabled the `linter` plugin in the editor category of `doom_modules.lua`

However i get the following error when editing javascript files.

![2021-12-14-172244_1320x548_scrot](https://user-images.githubusercontent.com/27077246/146048397-efcd5ce4-874f-45c2-8c0e-655b91b54a6a.png)

Any help would be appreciated

**Comment by emmanueltouzery** [comment]
for some reason it doesn't work for me either. I'm using 3.2.0. I enabled all the settings like @nulloneguy (except i'm testing with sh/ShellCheck instead of eslint. nvim-lint gets installed, and if I run `:lua require('lint').try_lint()` manually it works...

For some reason the autocmd from the init.lua doesn't appear to get run. For now I'm running `vim.cmd("au BufWinEnter,BufWritePost * lua require('lint').try_lint()")` manually at startup.

**Comment by connorgmeehan** [comment]
This is resolved in https://github.com/NTBBloodbath/doom-nvim/tree/next.  [Here](https://github.com/NTBBloodbath/doom-nvim/blob/next/lua/doom/modules/langs/css/init.lua) is an example of language support including linting via null-ls: 
And [here](https://github.com/NTBBloodbath/doom-nvim/blob/next/docs/modules.md#building-your-own-module) is documentation on creating custom modules, for personal use or to upstream
