### ISSUE TITLE
override plugin settings in doomrc

### ISSUE THREAD

**Issue by bketelsen** [NTBBloodbath/doom-nvim#23]
I want to change the file tree to stay open after I open a file.

the setting in the plugin is G.nim_tree_quit_on_open, so I changed it in my doomrc hoping that would load last and override the plugin setting.

Is there a specific place i can make this override where it will be loaded after the plugins?

Thanks for doom-nvim, I've already got a few friends using it too :)

**Comment by NTBBloodbath** [comment]
Hey, which doom-nvim branch are you using?

If you're using the main branch the only workaround for this will be directly modifying the plugin configurations. Otherwise if you're using the development branch you'll be able to change it with the [`Neovim` field](https://github.com/NTBBloodbath/doom-nvim/blob/develop/doomrc#L338-L343) in the doomrc.

Regards :)

**Comment by bketelsen** [comment]
Thanks.  I checked out `develop` but couldn't make it start. I didn't have time to dive too deeply into why, so I went back to `main` for now.  I'll close this, the feature is on the way.
