### ISSUE TITLE
Plugins doesnt install

### ISSUE THREAD

**Issue by 3JlOy-PYCCKUi** [NTBBloodbath/doom-nvim#260]
I wanted to install the plugin firenvim (https://github.com/glacambre/firenvim), I added it to plugins.lua exactly as firenvim README says (see screenschot), restarted neovim, saw a warning `[packer.nvim] [WARN <my time>] packer.lua:197: Plugin "firenvim" is used twice! (line 508)`, the command that told to execute after installing firenvim (`:call firenvim#install(0)`) failed because it was not found, also in the output `:PackerStatus` was no firenvim.
![firenvim](https://user-images.githubusercontent.com/46464602/143627691-611445e8-7e9c-4112-aa2c-1006eeeebab4.png)

**Comment by molleweide** [comment]
I believe the plugin is already being installed in 'modules/init.lua' if you enable it in doom_modules

**Comment by molleweide** [comment]
U need to enable it in doom modules

**Comment by 3JlOy-PYCCKUi** [comment]
Indeed, I didn't see it earlier. Thanks

**Comment by NTBBloodbath** [comment]
@3JlOy-PYCCKUi Hi, if you're using development branch you can enable firenvim in your doom_modules.lua file. It's at the bottom of all the modules definition.

That warning is because Doom already declares a firenvim entry (but disabled so it will not be installed) and you're adding another one in your custom plugins so yeah packer complains :p
