### ISSUE TITLE
Glaz language syntax support

### ISSUE THREAD

**Issue by StunxFS** [NTBBloodbath/doom-nvim#314]
### What is the feature, what would you like to be able to do?

Support the syntax of a programming language that I am doing.

Repo: https://github.com/glaz-lang/glaz

### What is the use case, why do you want this feature?

Extend support in editors for my language :)

### Possible Implementation (if applicable)

This could be used as a base: https://github.com/lite-xl/lite-xl-plugins/blob/master/plugins/language_glaz.lua

**Comment by NTBBloodbath** [comment]
Hey mate, hope you're doing well.

This is something that cannot be done in doom itself, this would require you _or someone else_ to make a (Neo)vim plugin with Vimscript syntax files and include it as a plugin in doom or any other (Neo)vim configuration. You can use Vlang plugins as a reference.

Another solution would be making a tree-sitter parser for your language and including a highlights injections file (see tree-sitter docs) and making a PR to [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) to officially support your parser, note that this solution works only for Neovim >= 0.5.0 and doesn't work for Vim.

I'll close this issue because it's not directly related to doom-nvim project.

Cheers
