### ISSUE TITLE
[SUGGESTION] convert colorscheme into plugin

### ISSUE THREAD

**Issue by samrath2007** [NTBBloodbath/doom-nvim#56]

**Comment by NTBBloodbath** [comment]
Hey, are you meaning converting `doom-one` into an optional plugin? It was the behavior a long time ago, but since is the default colorscheme (it's the flagship doom colorscheme) it can end spitting some errors complaining about the colorscheme `doom-one` was not found.

Actually because of these errors we are embedding the plugin directly in doom's source and you can change the colorscheme in the configurations if you don't like it _as it should be_.
