### ISSUE TITLE
leader 2 chars binding issue

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#71]
Hi again,

These bindings don't take effect from `doom_config.lua`

``` lua
        -- jumps
	    {'n', '<leader>ja', '<C-^>', opt },
	    {'n', '<leader>je', '<C-i>', opt }, -- newer cursor position in jump list
	    {'n', '<leader>jo', '<C-o>', opt }, -- older...
```

but it works with single char like `<leader>a`

**Comment by molleweide** [comment]
also, how does one reload the config?? I am really starting to like doom

**Comment by NTBBloodbath** [comment]
Hmm maybe it's because of which-key plugin? Let's try modifying the `lua/doom/modules/config/doom-whichkey.lua` and adding a `jump` category, hope it works.

**Comment by NTBBloodbath** [comment]
> also, how does one reload the config?? I am really starting to like doom

Doom will automatically reload its modules (e.g. keybindings, custom options) and the plugins configurations too (by running `:PackerCompile` when a `config/doom-X.lua` had changes) :)

**Comment by molleweide** [comment]
thanks for replying again!

i will try your suggestion and get back.

**Comment by molleweide** [comment]
> Hmm maybe it's because of which-key plugin? Let's try modifying the `lua/doom/modules/config/doom-whichkey.lua` and adding a `jump` category, hope it works.

Oh now i think i understand what you mean! Do you mean that maybe which-key is "blocking" leader key maps that fall outside of the specified tree in the config. This means that I have to duplicate all my maps in there also basically.

**Comment by molleweide** [comment]
yes then it works! i will add some jumpkeys and make a pr.

**Comment by molleweide** [comment]
> > also, how does one reload the config?? I am really starting to like doom
> 
> Doom will automatically reload its modules (e.g. keybindings, custom options) and the plugins configurations too (by running `:PackerCompile` when a `config/doom-X.lua` had changes) :)

I realize that forgot to mention more specifically how do I relead custom keybindings? 
Would I need a special command for this? Because commands like `so $MYVIMRC` doesn't work here right?
Currently I am restarting vim every time to refresh mappings.

**Comment by NTBBloodbath** [comment]
Hmm live-reloading in Lua is a bit more complex because of the `require` functions.

Basically there's a Lua table called `package.loaded` that contains all the Lua modules loaded, so by example you can do `package.loaded["doom.core"] = nil` to "unload" the Doom core module, and then require it again but this doesn't do the trick for this case.

At the moment you can write something like that in a custom function in your `doom_config.lua`:
```lua
functions = {
    reload_custom_options = function()
		-- Our handler for the user-defined settings
		local load_custom_options = require("doom.core.functions").load_custom_options
		-- Get the user-defined options, the 'nvim' field in our 'doom_config.lua'
		local custom_options = require("doom.core.config").load_config().nvim

		-- Iterate over all the custom options fields, e.g. global_variables, mappings, etc.
		for field, _ in pairs(custom_options) do
			-- Load the custom options again.
			-- This function takes two parameters, the options list and the options scope, e.g. mappings
			load_custom_options(custom_options[field], field)
		end
	end,
},
```

And lately in your mappings field in the same file, you could set a mapping for this function:
```lua
mappings = {
	{ "n", "rc", "<cmd>lua require('doom.core.config').load_config().nvim.functions.reload_custom_options()<CR>},
},
```

**Comment by molleweide** [comment]
wow thanks I will try this and report back

**Comment by NTBBloodbath** [comment]
Sure, also in case that it doesn't work you can try commenting [these lines](https://github.com/NTBBloodbath/doom-nvim/blob/main/lua/doom/core/functions/init.lua#L63-L65) locally because the custom functions are being called on launch and maybe this one can cause some issues.

And what I just said gave me an idea to improve doom's extensibility, I'll be implementing it this week :)
