### ISSUE TITLE
Idiomatic way to version control (dotfiling) doom configs?

### ISSUE THREAD

**Issue by starptr** [NTBBloodbath/doom-nvim#79]
Since `~/.config/doom-nvim/` is a git repo with this github repo as the remote, it's not trivial to add the `doomrc.lua`, `doom_config.lua`, and `plugins.lua` files to a dotfiles manager like `yadm`.

Is there a recommended way to do this? I was thinking that maybe one could fork the repo & add the fork as a submodule to yadm, but that's not a very clean solution (updates won't work without syncing the fork) (and for me personally I'd rather avoid submodules).

**Comment by kreisys** [comment]
Doom Emacs does this by keeping itself in `~/.config/emacs` and loading the user config from `~/.config/doom` which the user can decide whether they want to version control or not...

**Comment by starptr** [comment]
Right. It would be awesome if doom nvim can also implement a similar config structure such that doom itself and user configs are located separately, so that dotfile managers can play nicely with the user configs :)

**Comment by NTBBloodbath** [comment]
Hey, I'm pretty sure that it's gonna be useful _also I don't like the submodules idea_. Actually there are a lot of changes in the development version regarding to where is `doom-nvim` installed (now it's installed in `~/.config/nvim` by default instead of a custom path) so maybe we can use the same structure as Doom Emacs (`~/.config/nvim` for keeping `doom-nvim` and `~/.config/doom-nvim` for keeping the user configurations).

But I don't want to make the source too complex or keeping introducing breaking changes so we can make this a feature so you will be able to keep your `doom-nvim` configurations in two paths depending on your needs:

1. The default path (`~/.config/nvim`)
2. A custom path (`~/.config/doom-nvim` by default)

Let me know what do you think about so we can implement it soon.

Regards

**Comment by NTBBloodbath** [comment]
Hey, so I just pushed a few changes to implement it the way I said before and also added an entry to our [FAQ](https://github.com/NTBBloodbath/doom-nvim/blob/e21b84ffb9aacc4b41ddb7d50568c0911ecf5c9a/docs/faq.md#how-to-version-control-doom-nvim) (I'm thinking about moving it to a wiki entry when 3.1 is released as a stable version)

**Comment by starptr** [comment]
That sounds great, my setup is currently too wonky to try it out the dev branch but it looks nice & clean (and proven based on doom emacs)

**Comment by NTBBloodbath** [comment]
I'll be closing this because the feature was already implemented in the development version so I can have a better track of the next version milestone :slightly_smiling_face: 

Feel free to reopen this in the future if you're still facing issues while dotfiling doom-nvim
